[package]
name = "action_items_ecs_surrealdb"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
async-std = "1.13.0"
uuid = { workspace = true }

# SurrealDB dependencies - MUST use project fork SDK crate
surrealdb = { path = "../../forks/surrealdb/crates/sdk", features = ["kv-surrealkv"] }

# Common types and traits
action_items_common = { path = "../common" }

[lib]
name = "action_items_ecs_surrealdb"
path = "src/lib.rs"
# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"
