[package]
name = "action_items_native_macros"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[lib]
proc-macro = true
