//! Global hotkey events
//!
//! Events related to global hotkey activation and management.

use bevy::prelude::*;

/// Event fired when a global hotkey is activated
/// This event is now generated by proper event-driven callback system
#[derive(Event, Debug, Default)]
pub struct GlobalHotkeyEvent {
    /// Unique identifier for the activated hotkey
    pub id: u32,
}
