[package]
name = "action_items_ecs_search_aggregator"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Bevy ECS search aggregator plugin for Action Items launcher"

[dependencies]
bevy = { workspace = true }
action_items_common = { path = "../common" }
ecs-service-bridge = { path = "../ecs-service-bridge" }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["sync", "time", "rt"] }
uuid = { workspace = true, features = ["v4"] }
log = { workspace = true }

[lib]
name = "action_items_ecs_search_aggregator"
path = "src/lib.rs"

# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"

[dev-dependencies]
tokio-test = "0.4"