[package]
name = "action_items_ecs_fetch"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Bevy ECS HTTP client service wrapping reqwest with connection pooling, rate limiting, and security"

[dependencies]
bevy = { workspace = true }
reqwest = { version = "0.12.23", features = ["json", "stream", "gzip", "brotli", "hickory-dns", "rustls-tls"], default-features = false }
tokio = { workspace = true, features = ["sync", "time", "rt", "macros", "net"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-futures = "0.2.5"
governor = { version = "0.10.1", features = ["std", "dashmap"], default-features = false }
uuid = { workspace = true, features = ["v4"] }
thiserror = { workspace = true }
ahash = "0.8.12"
crossbeam-channel = { workspace = true }
bytes = "1.10.1"
http = "1.3.1"
url = "2.5.7"
ipnet = "2.11.0"
base64 = "0.22.1"
urlencoding = "2.1.3"
futures-util = "0.3.31"
fastrand = "2.3.0"
# action_items_ecs_cache = { path = "../ecs-cache" }  # Temporarily disabled due to goldylox compilation errors
sha2 = "0.10"
hex = "0.4.3"
blake3 = "1.8"
fnv = "1.0.7"

[lib]
name = "action_items_ecs_fetch"
path = "src/lib.rs"

[dev-dependencies]
tokio-test = "0.4"


[lints]
workspace = true

[features]
default = ["rustls-tls"]
rustls-tls = ["reqwest/rustls-tls"]
cache = []  # Disabled by default due to goldylox dependency issues
