[package]
name = "action_items_ecs_user_settings"
version = { workspace = true }
edition = { workspace = true }
description = "Bevy ECS user settings service with SurrealDB backend"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
toml = "0.9.7"
surrealdb = { path = "../../forks/surrealdb/crates/sdk", default-features = false }

# Database layer - uses existing ecs-surrealdb
action_items_ecs_surrealdb = { path = "../ecs-surrealdb" }

# Common types and XDG directories
action_items_common = { path = "../common", features = ["bevy"] }

[dev-dependencies]
tempfile = "3.8"

[features]
integration-tests = []

[lib]
name = "action_items_ecs_user_settings"
path = "src/lib.rs"

[lints.rust]
warnings = "warn"
unused = "warn"
