[package]
name = "ecs-service-bridge"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
description = "Bevy ECS plugin for inter-service communication and message routing"
license = "MIT OR Apache-2.0"
repository = "https://github.com/action-items/action-items"

[dependencies]
bevy = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full", "sync", "time", "rt-multi-thread"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
thiserror = "2"
uuid = { version = "1.18", features = ["v4", "serde"], default-features = false }
chrono = { version = "0.4", features = ["serde"], default-features = false }
crossbeam-channel = "0.5"
metrics = "0.24"
rustc-hash = "2"
rand = "0.9"
sha2 = "0.10"
rand_chacha = "0.9"
base64 = "0.22.1"
action_items_ecs_compression = { version = "0.1.0", path = "../ecs-compression" }

[dependencies.action_items_common]
path = "../common"

# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"
