[package]
name = "action_items_ecs_bluetooth"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
authors = ["Action Items Team"]
description = "Cross-platform Bluetooth operations for ECS applications"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cyrup-ai/action-items"

[dependencies]
bevy = { workspace = true }
thiserror = "2.0.16"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
tracing = "0.1.41"
tokio = { version = "1.47.1", features = ["full"] }

# Platform-specific dependencies
[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.2"
objc2-core-bluetooth = "0.3.1"
objc2-foundation = "0.3.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.0", features = [
    "Win32_Devices_Bluetooth",
    "Win32_Foundation",
    "Win32_System_Com",
] }

[target.'cfg(target_os = "linux")'.dependencies]
bluez-async = "0.8.2"
tokio = { version = "1.47.1", features = ["rt", "macros"] }

# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"

[dev-dependencies]
tokio-test = "0.4"
