[package]
name = "action_items_common"
edition.workspace = true
version.workspace = true
description = "Shared types and traits for action-items"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["chrono"] }
tracing-appender = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.11.2"
metrics = "0.24.2"
sysinfo = { workspace = true }
metrics-exporter-prometheus = "0.17.2"
once_cell = "1"
atomic = "0.6.1"
parking_lot = "0.12.4"
tokio = { version = "1.47", features = ["full"] }
dirs = "6.0.0"
wait-timeout = "0.2"
crossbeam-channel = { workspace = true }
libc = "0.2"
tikv-jemalloc-ctl = { workspace = true, features = ["profiling", "stats"], optional = true }
bevy = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "winbase", "minwinbase", "ntdef", "handleapi"] }

# Memory profiling dependencies (optional)
tikv-jemalloc-ctl = { workspace = true, optional = true }

# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"

[dev-dependencies]
arbitrary = "1.4.2"
assert_matches = "1.5.0"
fake = "4.4.0"
futures-test = "0.3.31"
insta = "1.43"
proptest = "1.7.0"
quickcheck = "1.0.3"
serde_test = "1.0.177"
serial_test = "3.2.0"
tempfile = "3.21.0"
tokio-test = "0.4.4"
tracing-test = "0.2.5"

[features]
jemalloc-profiling = ["tikv-jemalloc-ctl"]
dhat-heap = ["dhat"]
memory-testing = ["dhat"]
tikv-jemalloc-ctl = ["dep:tikv-jemalloc-ctl"]
bevy = ["dep:bevy"]

[dependencies.dhat]
version = "0.3"
optional = true
