[package]
name = "ecs-notifications"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
description = "Cross-platform system notifications with Bevy ECS integration"

[dependencies]
bevy = { workspace = true }
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread", "time"] }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
parking_lot = "0.12"
tracing = "0.1"
rand = "0.9"
url = "2"
uuid = { version = "1", features = ["v4", "serde"] }
regex = "1"
chrono = { version = "0.4", features = ["serde"] }

# macOS specific
[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-user-notifications = "0.3"
block2 = "0.6"

# Linux specific
[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "5.10", default-features = false, features = ["tokio"] }

# Windows specific
[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Data_Xml_Dom",
    "UI_Notifications",
    "Win32_Foundation",
] }

# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"

[dev-dependencies]
tokio-test = "0.4"
