[package]
name = "ecs-notifications"
version = "0.1.0"
edition = "2024"
description = "Cross-platform system notifications with Bevy ECS integration"

[dependencies]
bevy = { workspace = true }
tokio = { version = "1.0", features = ["sync", "rt"] }
thiserror = "2.0.16"
serde = { version = "1.0", features = ["derive"] }
parking_lot = "0.12"
tracing = "0.1"
rand = "0.9"
url = "2.5"
uuid = { version = "1.18", features = ["v4", "serde"] }
regex = "1.11"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"

# macOS specific
[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.2"
objc2-foundation = "0.3.1"
objc2-user-notifications = "0.3.1"
block2 = "0.6.1"

# Linux specific  
[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "5.10.0", default-features = false, features = ["tokio"] }

# Windows specific
[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.3", features = [
    "Data_Xml_Dom",
    "UI_Notifications",
    "Win32_Foundation",
] }


[dev-dependencies]
tokio-test = "0.4"
