[package]
name = "action_items_ecs_progress"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { workspace = true }
parking_lot = "0.12"
derive_more = { version = "2", features = ["full"] }
crossbeam-channel = { version = "0.5", optional = true }
ecs-task-management = { path = "../ecs-task-management" }

[features]
# Support for debug functionality (such as logging progress to console)
debug = []
assets = []
async = ["dep:crossbeam-channel"]

# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"

[dev-dependencies]
bevy = { workspace = true }
