[package]
name = "ecs-tls"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
description = "TLS certificate management with Bevy ECS integration"

[dependencies]
bevy = { workspace = true }
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread", "time", "fs"] }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1.41"
base64 = "0.22"
x509-parser = "0.18"
sha2 = "0.10"
hex = "0.4"
rustls = "0.23"
rustls-pemfile = "2"
webpki-roots = "1"
der = "0.7"
chrono = { version = "0.4", features = ["serde"] }
url = "2"
reqwest = { version = "0.12", features = ["rustls-tls"] }
anyhow = "1"
rcgen = { version = "0.14", features = ["x509-parser"] }
x509-cert = "0.2"
ring = "0.17"
once_cell = "1"
rand = "0.9"
x509-ocsp = "0.2"
zeroize = { version = "1", features = ["derive"] }
asn1 = "0.22"
hostname = "0.4"

# macOS specific - TCC permissions integration through ecs-permissions
[target.'cfg(target_os = "macos")'.dependencies]
action_items_ecs_permissions = { path = "../ecs-permissions" }
home = "0.5"
security-framework = "3"
core-foundation = "0.10.1"
base64 = "0.22"
x509-parser = "0.18"

# Linux specific
[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

# Windows specific
[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_Security_WinTrust",
    "Win32_Foundation",
    "Win32_System_SystemServices"
] }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3"

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"

[lib]
name = "ecs_tls"
path = "src/lib.rs"
