[package]
name = "action_items_ecs_deno"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
# Bevy ECS dependencies
bevy = { workspace = true }

# Deno runtime dependencies - aligned with serde_v8 0.271.0 and v8 140.2.0
deno_core = { version = "0.362.0" }
deno_console = { version = "0.218.0" }
deno_url = { version = "0.218.0" }
deno_webidl = { version = "0.218.0" }
deno_web = { version = "0.249.0" }
deno_error = { version = "0.7.0" }
deno_ops = { version = "0.238.0" }
serde_v8.workspace = true
v8.workspace = true
deno_path_util = { version = "0.6.1" }
deno_unsync = { version = "0.4.4" }

# Core dependencies
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["fs", "rt-multi-thread", "time"] }
futures = "0.3"
notify = "8.2.0"
tracing = "0.1"
uuid = { version = "1.18", features = ["v4", "serde"] }
bytes = "1"
thiserror = "2"

# Cross-platform system dependencies
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
mach2 = "0.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "psapi", "sysinfoapi", "errhandlingapi", "winnt"] }

[lib]
name = "action_items_ecs_deno"
path = "src/lib.rs"

# Re-enable warnings for this workspace package
[lints]

[lints.rust]
warnings = "warn"
unused = "warn"
unused_imports = "warn"
unused_variables = "warn"
unused_mut = "warn"
dead_code = "warn"
deprecated = "warn"
